### PR TITLE
fix-#1

### PR DESCRIPTION
**Pull request by jahlomp**
Fixed Media requiring issue at #1

### CODE REVIEW

**Comment by blakecallens** [comment]
Thanks for working on this. I think Media is an unused variable. Can you remove the line and see if the theme still runs?

**Comment by jahlomp** [comment]
Ok

**Comment by jahlomp** [comment]
Tested and it worked

**Comment by JahlomP** [comment]
Please help me with something. 

I want to show just a summary or description of each article instead of the full article on the home page.

**Comment by blakecallens** [comment]
Thanks, man!

**Comment by JahlomP** [comment]
please test

**Pull request merged**
